spring:
  application:
    name: "configserver"

  profiles:
    active: git
    #active: native #activating native profile

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Vinod155/Vin-config"
          default-label: origin
          timeout: 5  #if config server is not connected it will throw error
          clone-on-start: true # clone the github repo on startup
          force-pull: true #override all the local changes whenever you start
        #native:
          #search-locations: "file:/// D:/config"
          #search-locations: "classpath:/config" #locations of config

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"  #including actuator and allowing application to refresh without restart




#encryption key
encrypt:
  key: "vinIstheKeyForsu55ess2116"

server:
  port: 8071
