
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/" #configserver tells that we will connect to our configserver,optional means if we cannot find configserver then also

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false   # disabling the default routing
          lowerCaseServiceId: true # accepting the lower case url
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

    #start the application
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"  #including actuator and allowing application to refresh without restart

  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true






info:
  app:
    name: "gatewayserver"
    description: "Eazy bank Gateway Server"
    version: "1.0.0"

logging:
  level:
    com:
      example:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # telling atleast monitor 10 request and then conclude what to do
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000