spring:
  application:
    name: "eurekaserver"


  config:
    import: "optional:configserver:http://localhost:8071/"
  management:
    endpoints:
      web:
        exposure:
          include: "*"  #including actuator and allowing application to refresh without restart
    health:
      readiness:
        enabled: true
      liveness:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true